name: prose/ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '__pycache__'
      - '.pytest_cache'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          python -m poetry install --with dev
      - name: Test with pytest
        run: |
          python -m poetry run python -m pytest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          python -m poetry install --with dev
      - name: Test with pytest
        run: |
          python -m poetry run python -m pytest
